services:
  hugot:
    image: hugot:$commit_hash
    platform: linux/amd64
    container_name: hugot
    build:
      context: .
      dockerfile: ./Dockerfile
      target: hugot-build
    volumes:
      - $test_folder:/test
      - $test_folder/../scripts/run-unit-tests-container.sh:/run-unit-tests-container.sh
    environment:
      - HOST_UID=$host_uid
      - CI=$CI
      - HUGOT_BUILD_TAG=$HUGOT_BUILD_TAG
    command: /run-unit-tests-container.sh
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
