services:
  hugot:
    image: hugot:$commit_hash
    container_name: hugot
    build:
      context: .
      dockerfile: ./Dockerfile
      target: testing
    volumes:
      - $test_folder:/test
      - $test_folder/../scripts/run-unit-tests-container.sh:/run-unit-tests-container.sh
    environment:
      - HOST_UID=$host_uid
      - TEST_MODELS_FOLDER=/models
    command: /run-unit-tests-container.sh
