services:
  hugot:
    image: hugot:dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./test.Dockerfile
      target: hugot-build
    volumes:
      - $src_dir:/home/testuser/repositories/hugot
    entrypoint: ["tail", "-f", "/dev/null"]
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
