services:
  hugot:
    image: hugot:dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: building
    volumes:
      - $src_dir:/home/testuser/repositories/hugot
    entrypoint: ["tail", "-f", "/dev/null"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]