name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build and run tests
      run: make run-tests
    - name: print
      run: ls -la
    - uses: actions/upload-artifact@v4
      with:
        name: libtokenizers.a
        path: ./testTarget/libtokenizers.a
    - uses: actions/upload-artifact@v4
      with:
        name: onnxruntime.so
        path: ./testTarget/onnxruntime.so
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: libtokenizers.a
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: onnxruntime.so
          path: .
      - name: Display structure of downloaded files
        run: ls -R
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "libtokenizers.a, onnxruntime.so"
          generateReleaseNotes: true
          skipIfReleaseExists: true