name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  test:
      name: Run test suite
      runs-on: ubuntu-22.04
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run tests
        run: make run-tests
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes