name: Run tests

on: workflow_dispatch

permissions:
  contents: write
  checks: write

jobs:
  test:
      name: Run test suite
      runs-on: ubuntu-latest
      steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          go mod download
      - name: Build and run tests
        run: make run-tests
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: goveralls -coverprofile=./testTarget/unit/cover.out -service=github
      - uses: actions/upload-artifact@v4
        with:
          name: libtokenizers.a
          path: ./artifacts/libtokenizers.a
      - uses: actions/upload-artifact@v4
        with:
          name: onnxruntime.so
          path: ./artifacts/onnxruntime.so
      - uses: actions/upload-artifact@v4
        with:
          name: hugot-cli-linux-amd64 
          path: ./artifacts/hugot-cli-linux-amd64
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: './testTarget/unit/*.xml'
          fail_on_failure: true
          require_tests: true