name: Run tests

on: workflow_dispatch

permissions:
  contents: write

jobs:
  test:
      name: Run test suite
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and run tests
        run: make run-tests
      - name: print
        run: ls -la
      - uses: actions/upload-artifact@v4
        with:
          name: libtokenizers.a
          path: ./artifacts/libtokenizers.a
      - uses: actions/upload-artifact@v4
        with:
          name: onnxruntime.so
          path: ./artifacts/onnxruntime.so
      - uses: actions/upload-artifact@v4
        with:
          name: hugot-cli-linux-amd64 
          path: ./artifacts/hugot-cli-linux-amd64
